# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(321, 214)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(180, 180, 131, 23))
        self.pushButton.setObjectName("pushButton")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 301, 161))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.sort = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.sort.setObjectName("sort")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sort)
        self.roast = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.roast.setObjectName("roast")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.roast)
        self.beans = QtWidgets.QComboBox(self.formLayoutWidget)
        self.beans.setCurrentText("")
        self.beans.setObjectName("beans")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.beans)
        self.taste = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.taste.setObjectName("taste")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.taste)
        self.price = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.price.setMaximum(10000)
        self.price.setObjectName("price")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.price)
        self.volume = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.volume.setMaximum(10000)
        self.volume.setObjectName("volume")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.volume)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_3)

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Coffee"))
        self.pushButton.setText(_translate("Dialog", "Сохранить изменения"))
        self.label.setText(_translate("Dialog", "Сорт"))
        self.label_2.setText(_translate("Dialog", "Степень обжарки"))
        self.label_6.setText(_translate("Dialog", "В зернах/молотый"))
        self.label_5.setText(_translate("Dialog", "Описание"))
        self.label_4.setText(_translate("Dialog", "Цена"))
        self.label_3.setText(_translate("Dialog", "Объем"))
